"use client";
import {FormEvent, useState} from "react";
import SiteHeader from "../site-header";

export default function Contact(){
  const [sent,setSent]=useState(false);
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSent(true)}
  return <main><SiteHeader active="contact"/><section className="contact-hero"><p className="eyebrow light"><span/> Contact support</p><h1>Let’s make<br/><em>it easy.</em></h1><p>Questions about a plan, setup or channel availability? Send us the details and our support team will get back to you.</p></section><section className="section contact-section"><div className="contact-intro"><p className="eyebrow"><span/> We’re here to help</p><h2>One clear answer<br/><em>at a time.</em></h2><p>Tell us what you need and include your device model when relevant. Never share passwords, playlist URLs or private access keys in this form.</p><div className="contact-topics"><div><b>01</b><strong>Plans & billing</strong><span>Choosing a duration or checking an order</span></div><div><b>02</b><strong>Setup help</strong><span>Guidance for your TV, phone or computer</span></div><div><b>03</b><strong>Availability</strong><span>Ask about a region or category</span></div></div></div><form className="contact-form" onSubmit={submit}><label>Name<input name="name" required placeholder="Your name"/></label><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Topic<select name="topic" defaultValue="setup"><option value="setup">Setup help</option><option value="plans">Plans & billing</option><option value="availability">Channel availability</option><option value="other">Other question</option></select></label><label>Message<textarea name="message" required placeholder="How can we help?" rows={6}/></label><button className="button" type="submit">{sent?"Message ready ✓":"Send message →"}</button>{sent&&<p className="form-note">Thanks — your message is ready. Our team will reply as soon as possible.</p>}</form></section><section className="contact-strip"><b>Before you write</b><p>For your security, only share the information needed to answer your question. We will never ask for your passwords.</p></section><footer><a className="brand" href="/"><span className="brand-mark"><img src="/market-pro-logo.png" alt="Market Pro logo"/></span><span>MARKET <b>PRO</b></span></a><p>A simple, smooth and supported TV experience.</p><div><a href="/about-us">About us</a><a href="/terms-of-service">Terms of service</a><a href="/privacy-policy">Privacy policy</a></div><small>© 2026 Market Pro. All rights reserved.</small></footer></main>
}
