import {newArticles,bufferingSections,type Article} from "./editorial-data";
import {articleImages} from "./article-images";
export const channelRegions=[
 {slug:"united-states",name:"United States",count:"8,400+",intro:"Local, national, sports and entertainment categories from across the United States.",groups:["Local networks by state and city","Live sports and event coverage","National news","Entertainment and lifestyle","Movies and premium cinema","Kids, family and educational"]},
 {slug:"united-kingdom",name:"United Kingdom",count:"2,100+",intro:"A broad mix of British national, regional, sports and entertainment categories.",groups:["National television","Regional networks","Football and live sports","Movies and drama","News and documentaries","Music and children’s programming"]},
 {slug:"france-belgium",name:"France & Belgium",count:"1,900+",intro:"French-language viewing categories from France, Belgium and neighbouring regions.",groups:["French national television","Belgian French channels","Football and sports","Cinema and series","News and culture","Kids and documentaries"]},
 {slug:"spain-latin-america",name:"Spain & Latin America",count:"2,600+",intro:"Spanish-language categories covering Spain, Mexico, Central and South America.",groups:["Spain national and regional TV","Mexico and Central America","Argentina and Colombia","Football and live events","Telenovelas and entertainment","News, music and family"]},
 {slug:"arabic-countries",name:"Arabic countries",count:"3,400+",intro:"Arabic-language categories organised across North Africa, the Gulf and the Levant.",groups:["Morocco, Algeria and Tunisia","Egyptian entertainment","Gulf countries","Levant and Iraq","Arabic sports","News, cinema and family"]},
 {slug:"worldwide",name:"Worldwide",count:"11,600+",intro:"International categories spanning Europe, Africa, Asia and additional languages.",groups:["Germany, Austria and Switzerland","Italy and Portugal","Netherlands and Scandinavia","Africa and South Africa","India and South Asia","East Asia and international"]}
];

export const setupGuides=[
 {slug:"smart-tv",name:"Smart TV",summary:"Samsung, LG and other connected televisions",steps:["Connect the television to a stable internet connection.","Open the official app store for your TV brand.","Install a compatible, trusted media player.","Enter only the authorised access details supplied to you.","Restart the player and test a standard-quality stream before 4K."]},
 {slug:"fire-tv-stick",name:"Fire TV Stick",summary:"Amazon Fire TV and Fire TV Stick",steps:["Connect Fire TV to your television and Wi-Fi.","Search the Amazon Appstore for a compatible media player.","Install and open the player from your Apps screen.","Add your authorised playlist or account details.","Pin the app to your home screen and test playback."]},
 {slug:"android-tv",name:"Android TV",summary:"Android boxes, Google TV and smartphones",steps:["Open Google Play on the Android device.","Choose a reputable media player with clear privacy information.","Install the app and allow only necessary permissions.","Add the authorised playlist details supplied to you.","Use the player settings to select hardware decoding if needed."]},
 {slug:"apple-devices",name:"Apple devices",summary:"Apple TV, iPhone and iPad",steps:["Open the App Store on Apple TV, iPhone or iPad.","Install a compatible media player from a verified developer.","Open the app and choose the playlist or account login option.","Enter the authorised details securely.","Enable AirPlay only on trusted home networks."]},
 {slug:"computer",name:"Computer",summary:"Windows, macOS and compatible players",steps:["Use an up-to-date Windows or macOS computer.","Download a trusted media player from its official website.","Install it without optional third-party software.","Import your authorised playlist or enter account details.","Keep the player and operating system updated."]},
 {slug:"ibo-player-pro",name:"IBO Player Pro",summary:"Activation and playlist setup guide",steps:["Install IBO Player Pro from your device’s official app store.","Open the player and note the MAC address and device key.","Visit the official IBO Player Pro device-management page.","Add only a playlist you are legally authorised to access.","Restart the app and contact support if setup does not complete."]}
];

const originalPosts: Article[]=[
 {slug:"set-up-ibo-player-pro",tag:"Setup",title:"How to set up IBO Player Pro on your Smart TV",excerpt:"A responsible walkthrough for installing the player and adding an authorised playlist.",read:"8 min read",sections:[{h:"Before you begin",p:"IBO Player Pro is a media player and does not provide channels or subscriptions. Keep your authorised playlist details and television connected to a stable network."},{h:"Install and identify your device",p:"Download the app from the official store, open it and note the device information displayed on screen. Do not share these details publicly."},{h:"Add your playlist",p:"Use the official IBO management website, enter the device details and add only content you have permission to access. Restart the television app afterwards."},{h:"If it does not load",p:"Check spelling, subscription status and network stability. Restart the router and player before contacting support."}]},
 {slug:"fix-streaming-buffering",tag:"Troubleshooting",title:"Streaming keeps buffering? Try these 7 practical fixes",excerpt:"Improve Wi-Fi, check your device and identify common connection problems.",read:"6 min read",sections:[{h:"Test the connection",p:"Run a speed test near the viewing device and compare Wi-Fi with a wired connection when possible."},{h:"Reduce local congestion",p:"Pause large downloads, cloud backups and other high-bandwidth activity on the same network."},{h:"Restart cleanly",p:"Power off the player, television and router for a minute, then restart the router first."},{h:"Adjust quality",p:"Try HD before 4K and enable hardware decoding where the player supports it. Persistent issues may need provider support."}]},
 {slug:"choose-streaming-device",tag:"Guide",title:"Smart TV, Fire TV or Android TV: which device is right for you?",excerpt:"A simple comparison of popular ways to watch on your television.",read:"7 min read",sections:[{h:"Smart TV apps",p:"The simplest option uses the television’s built-in store, though app choice and updates vary by brand."},{h:"Fire TV",p:"Fire TV is compact and easy to operate, with a familiar app store and remote control."},{h:"Android TV and Google TV",p:"These devices offer broad app choice and flexible settings, which can suit more experienced users."},{h:"What to prioritise",p:"Choose a supported device with regular security updates, enough storage and strong Wi-Fi or Ethernet."}]},
 {slug:"protect-streaming-account",tag:"Security",title:"How to protect your streaming account and device",excerpt:"Passwords, trusted apps and privacy basics every viewer should know.",read:"5 min read",sections:[{h:"Use unique credentials",p:"Never reuse an important email or banking password for a media service."},{h:"Install from official sources",p:"Use recognised app stores and developer websites. Avoid modified packages from unknown download pages."},{h:"Keep access private",p:"Do not post device keys, MAC addresses or playlist links in public forums or screenshots."},{h:"Update regularly",p:"Keep the television, player and router firmware current to receive security fixes."}]},
 {slug:"hd-full-hd-4k-guide",tag:"Explainer",title:"HD, Full HD and 4K: what quality does your connection support?",excerpt:"Understand resolution, bandwidth and why a stable connection matters.",read:"5 min read",sections:[{h:"Resolution basics",p:"HD, Full HD and 4K describe increasing image detail. Higher resolution needs more bandwidth and capable hardware."},{h:"Stability matters",p:"A consistent connection is usually more important than a high peak speed. Wi-Fi interference can cause sudden drops."},{h:"Choose sensible quality",p:"Use HD on slower or mobile connections. Full HD and 4K work best on strong wired or modern Wi-Fi networks."},{h:"Device limitations",p:"Older televisions and low-powered boxes may struggle with newer video formats even when internet speed is sufficient."}]},
 {slug:"responsible-online-tv-guide",tag:"Legal",title:"A responsible guide to online TV and authorised content",excerpt:"What to check before using a playlist, player or streaming provider.",read:"9 min read",sections:[{h:"Players and content are different",p:"A media player is software. It does not automatically grant rights to channels, films or live events."},{h:"Check authorisation",p:"Use content supplied by licensed providers, your own media, public free-to-air sources or material you otherwise have permission to access."},{h:"Avoid suspicious claims",p:"Unlimited premium content at unrealistic prices, unclear ownership and anonymous payment demands can be warning signs."},{h:"Know your local rules",p:"Copyright and consumer laws differ by country. Seek qualified local advice when you are uncertain."}]}
];

export const blogPosts=[...newArticles,...originalPosts].map(p=>({...p,
 sections:p.slug==="fix-streaming-buffering"?bufferingSections:p.sections,
 updated:p.updated??(p.slug==="fix-streaming-buffering"?"2026-09-08":"2026-08-26"),
 ...articleImages[p.slug],
 sources:p.sources??[],
 read:Math.max(1,Math.ceil((p.slug==="fix-streaming-buffering"?bufferingSections:p.sections).map(s=>s.p).join(" ").split(/\s+/).length/200))+" min read"
}));
