export type Article = {slug:string;tag:string;title:string;excerpt:string;read:string;updated?:string;image?:string;sources?:{label:string;url:string}[];sections:{h:string;p:string}[]};
export const newArticles: Article[] = [
 {slug:'choose-tv-subscription',tag:'Buying guide',title:'Choosing an online TV subscription: a checklist before you pay',excerpt:'Check the device, channels, total cost and support process before choosing a subscription duration.',read:'4 min read',updated:'2026-09-08',image:'home-cinema-pro',sections:[
 {h:'Start with your viewing needs',p:'Write down the channels or types of programme you actually watch, your country and the device you plan to use. A large catalogue does not tell you whether a specific channel is available where you live. Ask for confirmation of the items on your list before payment. If one channel is the main reason for buying, make that clear in your request rather than assuming it is included.'},
 {h:'Check the exact device model',p:'A Smart TV label is not enough to establish app compatibility. Find the model number and software version in the television settings, then check the app store on that device. A player available on one model may not be available on another. Send the model to support before buying a separate streaming box or paying an app activation fee.'},
 {h:'Separate the three costs',p:'Your internet connection, media player and content subscription are separate purchases. A paid player does not necessarily include any channels. Ask whether the player has its own licence fee, how many simultaneous connections the service includes, and which currency the quoted amount uses. Compare the total for the subscription term; a monthly equivalent is useful only if you understand that the full term is paid together.'},
 {h:'Choose a duration you are comfortable with',p:'A shorter term limits your initial commitment while you check whether the setup suits you. A longer term may cost less per month but requires more money upfront. At Market Pro the displayed options are $14 for one month, $24 for three, $34 for six and $49 for twelve, in USD per connection. Confirm the final amount with support and do not assume that a lower monthly equivalent changes the payment schedule.'},
 {h:'Read delivery and refund conditions first',p:'Find out when activation starts, how access details are delivered and what happens if installation fails. Read the eligibility rules rather than relying on a guarantee badge. Market Pro describes a first-purchase refund request period of seven calendar days from activation, subject to its published conditions. Keep the order reference and payment confirmation so a request can be matched to your purchase.'},
 {h:'Make a useful pre-purchase enquiry',p:'A helpful message is: “I use [model] in [country], need [channels], and am considering [duration]. Please confirm compatibility, current availability, total price, player fees and activation steps.” Never include passwords or existing playlist links in a general enquiry. Review the reply and the payment recipient before paying. If an important answer is missing, resolve it first.'}
 ]},
 {slug:'wifi-or-ethernet-streaming',tag:'Troubleshooting',title:'Wi-Fi or Ethernet for streaming? Test before you buy new equipment',excerpt:'Compare your connection at the TV and decide whether a cable could help with interruptions.',read:'3 min read',updated:'2026-09-08',image:'streaming-device-pro',sources:[{label:'Google: troubleshoot streaming-device connections',url:'https://support.google.com/chromecast/answer/10109908?hl=en'}],sections:[
 {h:'Compare the same stream under the same conditions',p:'Use a programme you can access legitimately and keep the player, quality setting and television unchanged. Watch over Wi-Fi, then repeat over Ethernet if the device has a suitable port or supported adapter. Write down whether interruptions disappear, improve or remain. Changing the player and connection together makes it difficult to identify which change helped.'},
 {h:'Understand what a cable can change',p:'Ethernet removes the wireless link between your streaming device and router. Google includes a wired connection among its troubleshooting steps for supported streaming devices. It can help isolate home Wi-Fi problems, but it cannot repair an unavailable channel or a problem beyond your home network. Check adapter compatibility with the manufacturer before purchasing one.'},
 {h:'If you need to stay on Wi-Fi',p:'Try a temporary viewing position closer to the router and compare the result. Google also recommends checking firmware, restarting equipment and reducing interference around its streaming devices. Change one thing at a time and follow your router manufacturer’s instructions. A factory reset should not be the first experiment: it can erase configuration and create another problem to solve.'},
 {h:'Check competing activity',p:'Repeat the test while large downloads and backups are paused, then during normal household use. An improvement only during the quiet test suggests that shared capacity deserves attention. This comparison is more informative than buying a more expensive package based on a single speed result. Record the time of day because intermittent problems can be difficult to reproduce later.'},
 {h:'Give support a result they can use',p:'Report your device model, player version, whether the issue affects one or several streams, and the outcome of the wired comparison. For example: “Same programme and quality: Wi-Fi pauses every few minutes; Ethernet played for fifteen minutes without a pause.” That observation does not establish the final cause, but it helps support choose the next check. Do not share private access keys in screenshots.'}
 ]},
 {slug:'player-vs-subscription',tag:'Buying guide',title:'TV player vs subscription: what does each payment include?',excerpt:'Understand the difference between an app licence, access to content and your internet connection.',read:'3 min read',updated:'2026-09-08',image:'home-cinema-pro',sections:[
 {h:'A player is the software you use',p:'A media player is the application that opens a supported playlist or account. Installing or activating that application does not by itself establish access to a provider’s catalogue. Check the listing in your device’s official app store and read what the fee covers. Do not treat a player’s name or logo as evidence that a separate seller is endorsed by its developer.'},
 {h:'A subscription is a separate agreement',p:'A service subscription describes the access being offered, its duration, the connection allowance and the provider’s terms. Ask the seller which content is available in your country and what support is included. If an app displays a successful activation but no content, check whether service details still need to be supplied. Paying for the application a second time is not a useful first troubleshooting step.'},
 {h:'Keep the payment records separate',p:'Save each receipt with a short note explaining what it purchased: app licence or service term. If the issue is the player licence, its developer may be the relevant contact; if it is account activation or catalogue access, contact the service provider. For Market Pro orders, support checks the request before sending an individual payment link. Ask for the full amount and recipient details before proceeding.'},
 {h:'Check connections and device changes',p:'Compatibility with multiple device types does not mean unlimited simultaneous viewing. Ask how many connections the offer allows and what happens when replacing a television or reinstalling an app. A device-bound player licence may have its own transfer rules. Confirm those rules with the player developer, rather than assuming the service subscription covers the transfer.'},
 {h:'Before making either purchase',p:'Have the exact television or box model ready. Check that the intended player is available on it, ask whether a separate app fee is needed, and read the delivery and refund information for each purchase. Keep private account details out of public messages. If the relationship between an app payment and a service payment remains unclear, request a written explanation before buying.'}
 ]}
];
export const bufferingSections = [
 {h:'1. Find out how much is affected',p:'Try another programme and another legitimate streaming app on the same device. If only one channel fails, note its name and the time for support. If every app struggles, start with the device or network. This first comparison helps avoid changing your entire setup to solve a single-stream issue.'},
 {h:'2. Check the connection at the television',p:'Measure where you watch, not only beside the router. Repeat at the time interruptions usually occur. A fast result on a nearby phone does not establish how reliably the television receives data. Note whether the problem is constant or appears in bursts; both observations are useful when asking for help.'},
 {h:'3. Compare a wired connection',p:'Where your device supports it, test an Ethernet cable or a manufacturer-supported adapter. Keep the programme and video quality unchanged. If playback improves, investigate the wireless link before replacing the player. If it does not improve, keep checking rather than assuming that a more expensive router will solve it.'},
 {h:'4. Pause competing downloads',p:'Temporarily pause large downloads, cloud backups and other heavy traffic in the household. Repeat the same playback test. Restore normal use afterwards and compare. If interruptions occur only when several people are active, document that pattern before discussing your internet plan with the provider.'},
 {h:'5. Restart without erasing settings',p:'Close the player and restart the viewing device. If needed, restart the router according to its manufacturer’s instructions and wait for connectivity to return. Avoid a factory reset as an early step: it can remove saved network and account settings. Never delete your only copy of access details while troubleshooting.'},
 {h:'6. Lower quality and check updates',p:'Try a lower video quality when the player offers the option. Check for official updates to the player and device software. If lower quality works consistently, record that result for support. Do not install modified applications or grant unexpected permissions as a shortcut to better playback.'},
 {h:'7. Send a clear report',p:'Provide the device model, player version, approximate time, affected programmes and the checks already tried. State whether Ethernet or lower quality changed the result. Ask support to investigate if the problem persists. Hide playlist URLs and account keys in screenshots; they are not needed in a public troubleshooting post.'}
];
