"use client";

import { useEffect, useRef } from "react";

import {useLanguage,setLanguage} from "./language-preference";
import {usePathname} from "next/navigation";

const fr: Record<string,string> = {
  "Benefits":"Avantages","Plans":"Nos offres","Devices":"Appareils","View plans":"Voir les offres",
  "Online TV service · Support 7 days a week":"Service TV en ligne · Assistance 7j/7","Your entertainment.":"Votre divertissement.","Simply.":"Simplement.",
  "Enjoy your content on every screen with fast activation, quality adapted to your connection and a team ready to help.":"Retrouvez vos contenus sur tous vos écrans avec une activation rapide, une qualité adaptée à votre connexion et une équipe disponible pour vous accompagner.",
  "Explore plans":"Découvrir les offres","How does it work?":"Comment ça marche ?","✓ Fast activation":"✓ Activation rapide","✓ Support 7 days a week":"✓ Assistance 7j/7","✓ 7-day guarantee":"✓ Garantie 7 jours","Ultra":"Ultra","high definition":"haute définition","PREMIUM EXPERIENCE":"EXPÉRIENCE PREMIUM",
  "international channels":"chaînes internationales","movies and series":"films et séries","announced availability":"disponibilité annoncée","responsive support":"assistance réactive",
  "Why Market Pro":"Pourquoi Market Pro","Everything you need.":"Tout ce qu’il faut.","Nothing complicated.":"Rien de compliqué.","Crystal-clear picture":"Une image nette","SD, HD, Full HD and 4K quality depending on the content, your device and connection.":"Qualité SD, HD, Full HD et 4K selon le contenu, l’appareil et votre connexion.","Your favourite screens":"Vos écrans préférés","A service compatible with connected TVs, mobile devices and computers.":"Un service compatible avec les téléviseurs connectés, mobiles et ordinateurs.","Real guidance":"Un vrai accompagnement","Our team guides you through installation and answers your questions.":"Notre équipe vous guide lors de l’installation et répond à vos questions.",
  "Clear pricing":"Des tarifs transparents","Choose your":"Choisissez votre","plan.":"formule.","Every plan includes the same features. Only the duration changes.":"Les mêmes fonctionnalités dans chaque formule. Seule la durée change.","Most popular":"Le plus choisi","per connection":"pour 1 connexion","Fast activation":"Activation rapide","Live TV and catalogue":"TV en direct et catalogue","Multi-device compatible":"Compatible multiappareil","Support 7 days a week":"Assistance 7j/7","Choose this plan":"Choisir cette offre",
  "Everywhere with you":"Partout avec vous","One subscription.":"Un abonnement.","All your screens.":"Tous vos écrans.","We help you set up the service on your device, step by step.":"Nous vous aidons à configurer le service sur votre appareil, étape par étape.","Computer":"Ordinateur",
  "Easy setup":"Démarrage facile","Ready in":"Prêt en","three steps.":"trois étapes.","Choose":"Choisissez","Select the duration that suits you.":"Sélectionnez la durée qui vous convient.","Receive":"Recevez","Your access details and instructions arrive quickly.":"Vos accès et les instructions arrivent rapidement.","Enjoy":"Profitez","Install the service with help from our team.":"Installez le service avec l’aide de notre équipe.",
  "Customer reviews":"Avis clients","An experience that":"Une expérience qui","makes a difference.":"fait la différence.","Presentation examples — replace with verified customer reviews before commercial publication.":"Exemples de présentation — à remplacer par des avis clients vérifiés avant publication commerciale.","“Fast installation and very clear guidance. Everything was ready in just a few minutes.”":"“Installation rapide et explications très claires. Tout était prêt en quelques minutes.”","“The picture is smooth and support guided me through setup on my Smart TV.”":"“L’image est fluide et le support m’a guidé sur ma Smart TV sans difficulté.”","“A simple interface, a wide choice and, above all, a team that is available.”":"“Une interface simple, un choix très large et surtout une équipe disponible.”","Review example · France":"Exemple d’avis · France","Review example · Belgium":"Exemple d’avis · Belgique","Review example · Switzerland":"Exemple d’avis · Suisse",
  "Frequently asked questions":"Questions fréquentes","Need some":"Besoin d’un","clarification?":"éclaircissement ?","Our team is available if you cannot find your answer here.":"Notre équipe reste disponible si vous ne trouvez pas votre réponse ici.","Contact support →":"Contacter l’assistance →","Which devices are compatible?":"Quels appareils sont compatibles ?","Smart TV, Android TV, Fire TV, Apple TV, smartphones, tablets and computers.":"Smart TV, Android TV, Fire TV, Apple TV, smartphone, tablette et ordinateur.","What internet speed do I need?":"Quel débit internet faut-il ?","A stable connection is essential. Available quality depends on your speed and device.":"Une connexion stable est essentielle. La qualité disponible dépend de votre débit et de l’appareil utilisé.","Do you offer a guarantee?":"Proposez-vous une garantie ?","Yes. Subscriptions include a 7-day money-back guarantee, subject to our terms.":"Oui, les abonnements sont couverts par une garantie de remboursement de 7 jours, selon nos conditions.",
  "A simple, smooth and supported TV experience.":"Une expérience TV simple, fluide et accompagnée.","Terms & conditions":"Conditions générales","Refund policy":"Remboursement","© 2026 Market Pro. All rights reserved. Use this service only for content you are authorised to access.":"© 2026 Market Pro. Tous droits réservés. Utilisez ce service uniquement pour des contenus auxquels vous êtes autorisé à accéder."
};

const es: Record<string,string> = {
  "Benefits":"Ventajas","Plans":"Planes","Devices":"Dispositivos","View plans":"Ver planes","Online TV service · Support 7 days a week":"Servicio de TV en línea · Asistencia 7 días","Your entertainment.":"Tu entretenimiento.","Simply.":"Sin complicaciones.","Enjoy your content on every screen with fast activation, quality adapted to your connection and a team ready to help.":"Disfruta de tus contenidos en todas tus pantallas, con activación rápida, calidad adaptada a tu conexión y un equipo listo para ayudarte.","Explore plans":"Ver los planes","How does it work?":"¿Cómo funciona?","✓ Fast activation":"✓ Activación rápida","✓ Support 7 days a week":"✓ Asistencia 7 días","✓ 7-day guarantee":"✓ Garantía de 7 días","high definition":"alta definición","PREMIUM EXPERIENCE":"EXPERIENCIA PREMIUM","international channels":"canales internacionales","movies and series":"películas y series","announced availability":"disponibilidad anunciada","responsive support":"asistencia rápida",
  "Why Market Pro":"Por qué Market Pro","Everything you need.":"Todo lo que necesitas.","Nothing complicated.":"Sin complicaciones.","Crystal-clear picture":"Imagen nítida","SD, HD, Full HD and 4K quality depending on the content, your device and connection.":"Calidad SD, HD, Full HD y 4K según el contenido, el dispositivo y la conexión.","Your favourite screens":"Tus pantallas favoritas","A service compatible with connected TVs, mobile devices and computers.":"Un servicio compatible con televisores conectados, móviles y ordenadores.","Real guidance":"Ayuda de verdad","Our team guides you through installation and answers your questions.":"Nuestro equipo te guía durante la instalación y responde tus preguntas.",
  "Clear pricing":"Precios claros","Choose your":"Elige tu","plan.":"plan.","Every plan includes the same features. Only the duration changes.":"Todos los planes incluyen las mismas funciones. Solo cambia la duración.","Most popular":"Más elegido","per connection":"por conexión","Fast activation":"Activación rápida","Live TV and catalogue":"TV en directo y catálogo","Multi-device compatible":"Compatible con varios dispositivos","Support 7 days a week":"Asistencia 7 días","Choose this plan":"Elegir este plan",
  "Everywhere with you":"Siempre contigo","One subscription.":"Una suscripción.","All your screens.":"Todas tus pantallas.","We help you set up the service on your device, step by step.":"Te ayudamos a configurar el servicio en tu dispositivo, paso a paso.","Computer":"Ordenador","Easy setup":"Inicio sencillo","Ready in":"Listo en","three steps.":"tres pasos.","Choose":"Elige","Select the duration that suits you.":"Selecciona la duración que más te convenga.","Receive":"Recibe","Your access details and instructions arrive quickly.":"Recibe rápidamente tus datos de acceso e instrucciones.","Enjoy":"Disfruta","Install the service with help from our team.":"Instala el servicio con la ayuda de nuestro equipo.",
  "Customer reviews":"Opiniones de clientes","An experience that":"Una experiencia que","makes a difference.":"marca la diferencia.","Presentation examples — replace with verified customer reviews before commercial publication.":"Ejemplos de presentación: sustitúyelos por opiniones verificadas antes de la publicación comercial.","“Fast installation and very clear guidance. Everything was ready in just a few minutes.”":"“Instalación rápida e instrucciones muy claras. Todo estuvo listo en pocos minutos.”","“The picture is smooth and support guided me through setup on my Smart TV.”":"“La imagen es fluida y el soporte me guio para configurar mi Smart TV.”","“A simple interface, a wide choice and, above all, a team that is available.”":"“Una interfaz sencilla, muchas opciones y, sobre todo, un equipo disponible.”","Review example · France":"Ejemplo de opinión · Francia","Review example · Belgium":"Ejemplo de opinión · Bélgica","Review example · Switzerland":"Ejemplo de opinión · Suiza",
  "Frequently asked questions":"Preguntas frecuentes","Need some":"¿Necesitas alguna","clarification?":"aclaración?","Our team is available if you cannot find your answer here.":"Nuestro equipo está disponible si no encuentras aquí la respuesta.","Contact support →":"Contactar con soporte →","Which devices are compatible?":"¿Qué dispositivos son compatibles?","Smart TV, Android TV, Fire TV, Apple TV, smartphones, tablets and computers.":"Smart TV, Android TV, Fire TV, Apple TV, móviles, tabletas y ordenadores.","What internet speed do I need?":"¿Qué velocidad de internet necesito?","A stable connection is essential. Available quality depends on your speed and device.":"Una conexión estable es esencial. La calidad disponible depende de la velocidad y del dispositivo.","Do you offer a guarantee?":"¿Ofrecéis garantía?","Yes. Subscriptions include a 7-day money-back guarantee, subject to our terms.":"Sí. Las suscripciones incluyen una garantía de devolución de 7 días, sujeta a nuestras condiciones.","A simple, smooth and supported TV experience.":"Una experiencia de TV sencilla, fluida y acompañada.","Terms & conditions":"Términos y condiciones","Refund policy":"Reembolsos","Contact":"Contacto","© 2026 Market Pro. All rights reserved. Use this service only for content you are authorised to access.":"© 2026 Market Pro. Todos los derechos reservados. Usa este servicio solo para contenidos a los que estés autorizado a acceder."
};

Object.assign(fr,{"Channel list":"Liste des chaînes","Set up":"Installation","Plans":"Offres","Explore the catalogue":"Explorer le catalogue","Channel":"Liste des","list.":"chaînes.","Browse a broad selection organised by country, language and category. Availability may change as the catalogue is updated.":"Parcourez une large sélection organisée par pays, langue et catégorie. La disponibilité peut évoluer avec les mises à jour du catalogue.","live channels":"chaînes en direct","countries":"pays","where available":"selon disponibilité","Find your favourites":"Trouvez vos favoris","Made for a":"Pensé pour un","world of choice.":"monde de choix.","Use the categories below as a guide. Contact support to confirm a specific channel before ordering.":"Utilisez les catégories ci-dessous comme guide. Contactez le support pour confirmer une chaîne précise avant de commander.","United States":"États-Unis","United Kingdom":"Royaume-Uni","France & Belgium":"France et Belgique","Spain & Latin America":"Espagne et Amérique latine","Arabic countries":"Pays arabes","Worldwide":"Monde entier","Local networks":"Chaînes locales","Sports":"Sports","News":"Actualités","Entertainment":"Divertissement","Kids & family":"Jeunesse et famille","Documentaries":"Documentaires","Important":"Important","Market Pro is intended only for content that you are legally authorised to access. Channel availability is not guaranteed and may vary by region.":"Market Pro est destiné uniquement aux contenus auxquels vous êtes légalement autorisé à accéder. La disponibilité des chaînes n’est pas garantie et peut varier selon la région.","Ask about a channel →":"Demander une chaîne →",
"Step-by-step help":"Aide étape par étape","Set up in":"Installation en","minutes.":"quelques minutes.","Choose your device and follow a simple guide. Keep your activation details nearby before you begin.":"Choisissez votre appareil et suivez un guide simple. Gardez vos informations d’activation à portée de main.","Choose your device":"Choisissez votre appareil","Where do you":"Où voulez-vous","want to watch?":"regarder ?","Our instructions cover the most popular devices and media players.":"Nos instructions couvrent les appareils et lecteurs les plus populaires.","setup":"d’installation","Open guide →":"Ouvrir le guide →","Quick":"Installation","setup.":"rapide.","IBO Player Pro is a media player and does not include channels. You must use only playlists and content you are authorised to access.":"IBO Player Pro est un lecteur multimédia et ne contient aucune chaîne. Utilisez uniquement des playlists et contenus auxquels vous êtes autorisé à accéder.","Install the player":"Installer le lecteur","Download IBO Player Pro from the official app store available on your device.":"Téléchargez IBO Player Pro depuis la boutique officielle de votre appareil.","Note your device details":"Noter les informations de l’appareil","Open the app and securely note the MAC address and device key shown on screen.":"Ouvrez l’application et notez de façon sécurisée l’adresse MAC et la clé affichées.","Add your authorised playlist":"Ajouter votre playlist autorisée","Use the official IBO Player Pro management page and enter the access details provided to you.":"Utilisez la page officielle de gestion IBO Player Pro et saisissez les accès qui vous ont été fournis.","Restart and enjoy":"Redémarrer et profiter","Restart the player to load your authorised content. Contact support if you need help.":"Redémarrez le lecteur pour charger votre contenu autorisé. Contactez le support si nécessaire.",
"Market Pro journal":"Journal Market Pro","Watch smarter.":"Regardez mieux.","Learn more.":"Apprenez davantage.","Clear guides for setup, troubleshooting, devices and responsible streaming.":"Des guides clairs sur l’installation, le dépannage, les appareils et le streaming responsable.","Latest articles":"Derniers articles","All":"Tous","Devices":"Appareils","Guides":"Guides","Read article →":"Lire l’article →","Practical tips":"Conseils pratiques","Good advice,":"De bons conseils,","no noise.":"sans bruit.","New setup guides and streaming tips are added regularly.":"De nouveaux guides et conseils sont ajoutés régulièrement.","Ask a question":"Poser une question"});

Object.assign(es,{"Channel list":"Lista de canales","Set up":"Instalación","Plans":"Planes","Explore the catalogue":"Explora el catálogo","Channel":"Lista de","list.":"canales.","Browse a broad selection organised by country, language and category. Availability may change as the catalogue is updated.":"Explora una amplia selección organizada por país, idioma y categoría. La disponibilidad puede cambiar con las actualizaciones.","live channels":"canales en directo","countries":"países","where available":"cuando esté disponible","Find your favourites":"Encuentra tus favoritos","Made for a":"Creado para un","world of choice.":"mundo de opciones.","Use the categories below as a guide. Contact support to confirm a specific channel before ordering.":"Usa las categorías como guía. Contacta con soporte para confirmar un canal antes de comprar.","United States":"Estados Unidos","United Kingdom":"Reino Unido","France & Belgium":"Francia y Bélgica","Spain & Latin America":"España y Latinoamérica","Arabic countries":"Países árabes","Worldwide":"Todo el mundo","Local networks":"Canales locales","News":"Noticias","Entertainment":"Entretenimiento","Kids & family":"Infantil y familia","Documentaries":"Documentales","Important":"Importante","Market Pro is intended only for content that you are legally authorised to access. Channel availability is not guaranteed and may vary by region.":"Market Pro está destinado únicamente a contenidos a los que estés legalmente autorizado a acceder. La disponibilidad puede variar según la región.","Ask about a channel →":"Consultar un canal →",
"Step-by-step help":"Ayuda paso a paso","Set up in":"Configura en","minutes.":"minutos.","Choose your device and follow a simple guide. Keep your activation details nearby before you begin.":"Elige tu dispositivo y sigue una guía sencilla. Ten a mano tus datos de activación.","Choose your device":"Elige tu dispositivo","Where do you":"¿Dónde quieres","want to watch?":"verlo?","Our instructions cover the most popular devices and media players.":"Nuestras instrucciones cubren los dispositivos y reproductores más populares.","setup":"de instalación","Open guide →":"Abrir guía →","Quick":"Configuración","setup.":"rápida.","IBO Player Pro is a media player and does not include channels. You must use only playlists and content you are authorised to access.":"IBO Player Pro es un reproductor multimedia y no incluye canales. Usa solo listas y contenidos autorizados.","Install the player":"Instala el reproductor","Download IBO Player Pro from the official app store available on your device.":"Descarga IBO Player Pro desde la tienda oficial de tu dispositivo.","Note your device details":"Anota los datos del dispositivo","Open the app and securely note the MAC address and device key shown on screen.":"Abre la aplicación y anota de forma segura la dirección MAC y la clave mostradas.","Add your authorised playlist":"Añade tu lista autorizada","Use the official IBO Player Pro management page and enter the access details provided to you.":"Usa la página oficial de gestión de IBO Player Pro e introduce tus datos de acceso.","Restart and enjoy":"Reinicia y disfruta","Restart the player to load your authorised content. Contact support if you need help.":"Reinicia el reproductor para cargar tu contenido autorizado. Contacta con soporte si necesitas ayuda.",
"Market Pro journal":"Revista Market Pro","Watch smarter.":"Mira mejor.","Learn more.":"Aprende más.","Clear guides for setup, troubleshooting, devices and responsible streaming.":"Guías claras sobre instalación, solución de problemas, dispositivos y streaming responsable.","Latest articles":"Últimos artículos","All":"Todos","Devices":"Dispositivos","Guides":"Guías","Read article →":"Leer artículo →","Practical tips":"Consejos prácticos","Good advice,":"Buenos consejos,","no noise.":"sin ruido.","New setup guides and streaming tips are added regularly.":"Añadimos regularmente nuevas guías y consejos.","Ask a question":"Hacer una pregunta"});

Object.assign(fr,{"Home":"Accueil","Pricing":"Tarifs","About us":"À propos","Contact":"Contact"});
Object.assign(es,{"Home":"Inicio","Pricing":"Precios","About us":"Quiénes somos","Contact":"Contacto"});

Object.assign(fr,{"Contact support":"Contacter l’assistance","Let’s make":"Faisons les choses","it easy.":"simplement.","Questions about a plan, setup or channel availability? Send us the details and our support team will get back to you.":"Une question sur une offre, une installation ou un canal ? Envoyez-nous les détails et notre équipe vous répondra.","We’re here to help":"Nous sommes là pour vous aider","One clear answer":"Une réponse claire","at a time.":"à chaque fois.","Tell us what you need and include your device model when relevant. Never share passwords, playlist URLs or private access keys in this form.":"Expliquez-nous votre besoin et indiquez votre appareil si nécessaire. Ne partagez jamais de mot de passe, d’URL de playlist ou de clé privée.","Plans & billing":"Offres et facturation","Choosing a duration or checking an order":"Choisir une durée ou vérifier une commande","Setup help":"Aide à l’installation","Guidance for your TV, phone or computer":"Conseils pour TV, téléphone ou ordinateur","Availability":"Disponibilité","Ask about a region or category":"Demander une région ou catégorie","Name":"Nom","Your name":"Votre nom","Topic":"Sujet","Message":"Message","How can we help?":"Comment pouvons-nous vous aider ?","Send message →":"Envoyer le message →","Message ready ✓":"Message prêt ✓","Thanks — your message is ready. Our team will reply as soon as possible.":"Merci — votre message est prêt. Notre équipe répondra dès que possible.","Before you write":"Avant d’écrire","For your security, only share the information needed to answer your question. We will never ask for your passwords.":"Pour votre sécurité, partagez uniquement les informations nécessaires. Nous ne demanderons jamais vos mots de passe."});
Object.assign(es,{"Contact support":"Contactar con soporte","Let’s make":"Hagámoslo","it easy.":"fácil.","Questions about a plan, setup or channel availability? Send us the details and our support team will get back to you.":"¿Tienes preguntas sobre un plan, la configuración o los canales? Envíanos los detalles y nuestro equipo responderá.","We’re here to help":"Estamos aquí para ayudarte","One clear answer":"Una respuesta clara","at a time.":"cada vez.","Tell us what you need and include your device model when relevant. Never share passwords, playlist URLs or private access keys in this form.":"Dinos qué necesitas e indica tu dispositivo cuando sea necesario. Nunca compartas contraseñas, URL de listas ni claves privadas.","Plans & billing":"Planes y facturación","Choosing a duration or checking an order":"Elegir duración o consultar pedido","Setup help":"Ayuda de configuración","Guidance for your TV, phone or computer":"Ayuda para TV, móvil u ordenador","Availability":"Disponibilidad","Ask about a region or category":"Consultar región o categoría","Name":"Nombre","Your name":"Tu nombre","Topic":"Tema","Message":"Mensaje","How can we help?":"¿Cómo podemos ayudarte?","Send message →":"Enviar mensaje →","Message ready ✓":"Mensaje listo ✓","Thanks — your message is ready. Our team will reply as soon as possible.":"Gracias — tu mensaje está listo. Nuestro equipo responderá pronto.","Before you write":"Antes de escribir","For your security, only share the information needed to answer your question. We will never ask for your passwords.":"Por seguridad, comparte solo lo necesario. Nunca te pediremos tus contraseñas."});
Object.assign(fr,{"Before you start":"Avant de commencer","Need help? →":"Besoin d’aide ? →","Setup complete?":"Installation terminée ?","Explore channel categories":"Explorer les catégories","Need more help?":"Besoin d’aide ?","View setup guides":"Voir les guides d’installation","Responsible use":"Utilisation responsable","Market Pro guide":"Guide Market Pro","Practical information designed to help you make informed, responsible choices.":"Des informations pratiques pour vous aider à faire des choix éclairés et responsables.","Back to blog":"Retour au blog"});
Object.assign(es,{"Before you start":"Antes de empezar","Need help? →":"¿Necesitas ayuda? →","Setup complete?":"¿Configuración completa?","Explore channel categories":"Explorar categorías","Need more help?":"¿Necesitas más ayuda?","View setup guides":"Ver guías de configuración","Responsible use":"Uso responsable","Market Pro guide":"Guía Market Pro","Practical information designed to help you make informed, responsible choices.":"Información práctica para tomar decisiones informadas y responsables.","Back to blog":"Volver al blog"});
Object.assign(fr,{"Review from · France":"Avis de · France","Review from · Belgium":"Avis de · Belgique","Review from · Switzerland":"Avis de · Suisse"});
Object.assign(es,{"Review from · France":"Opinión de · Francia","Review from · Belgium":"Opinión de · Bélgica","Review from · Switzerland":"Opinión de · Suiza"});
Object.assign(fr,{"Start your order":"Commencez votre commande","One last step.":"Une dernière étape.","You’re almost ready.":"Vous y êtes presque.","Choose your offer and send your request securely via WhatsApp. We will send you a PayPal payment link after checking your order.":"Choisissez votre offre et envoyez votre demande de façon sécurisée via WhatsApp. Nous vous enverrons un lien de paiement PayPal après vérification de votre commande.","Simple & secure":"Simple et sécurisé","Your order,":"Votre commande,","your choice.":"votre choix.","We ask only for the details needed to respond to your request. We do not collect card details on this website.":"Nous demandons uniquement les informations nécessaires pour répondre à votre demande. Nous ne collectons aucune donnée de carte bancaire sur ce site.","Send your order request on WhatsApp":"Envoyez votre demande de commande sur WhatsApp","Receive your individual PayPal payment link":"Recevez votre lien de paiement PayPal individuel","Receive authorised service details after confirmed payment":"Recevez les informations du service autorisé après confirmation du paiement","WhatsApp number":"Numéro WhatsApp","Selected offer":"Offre choisie","I agree to be contacted on WhatsApp about this order.":"J’accepte d’être contacté(e) sur WhatsApp au sujet de cette commande.","Continue on WhatsApp":"Continuer sur WhatsApp","Opening WhatsApp with your order details…":"Ouverture de WhatsApp avec les détails de votre commande…","By continuing, you confirm that you will use the service only with content you are authorised to access.":"En continuant, vous confirmez utiliser le service uniquement pour des contenus auxquels vous êtes autorisé(e) à accéder."});
Object.assign(es,{"Start your order":"Inicia tu pedido","One last step.":"Un último paso.","You’re almost ready.":"Ya casi está.","Choose your offer and send your request securely via WhatsApp. We will send you a PayPal payment link after checking your order.":"Elige tu oferta y envía tu solicitud de forma segura por WhatsApp. Te enviaremos un enlace de pago de PayPal tras revisar el pedido.","Simple & secure":"Simple y seguro","Your order,":"Tu pedido,","your choice.":"tu elección.","We ask only for the details needed to respond to your request. We do not collect card details on this website.":"Pedimos solo los datos necesarios para responder a tu solicitud. No recopilamos datos de tarjeta en este sitio.","Send your order request on WhatsApp":"Envía tu solicitud de pedido por WhatsApp","Receive your individual PayPal payment link":"Recibe tu enlace de pago de PayPal individual","Receive authorised service details after confirmed payment":"Recibe los datos del servicio autorizado tras confirmar el pago","WhatsApp number":"Número de WhatsApp","Selected offer":"Oferta elegida","I agree to be contacted on WhatsApp about this order.":"Acepto que me contacten por WhatsApp sobre este pedido.","Continue on WhatsApp":"Continuar en WhatsApp","Opening WhatsApp with your order details…":"Abriendo WhatsApp con los datos de tu pedido…","By continuing, you confirm that you will use the service only with content you are authorised to access.":"Al continuar, confirmas que usarás el servicio solo con contenidos a los que estés autorizado a acceder."});
Object.assign(fr,{"Continue on WhatsApp →":"Continuer sur WhatsApp →","Opening WhatsApp…":"Ouverture de WhatsApp…","Opening WhatsApp with your message…":"Ouverture de WhatsApp avec votre message…"});
Object.assign(es,{"Continue on WhatsApp →":"Continuar en WhatsApp →","Opening WhatsApp…":"Abriendo WhatsApp…","Opening WhatsApp with your message…":"Abriendo WhatsApp con tu mensaje…"});

export default function LanguageSwitcher(){
  const lang=useLanguage();
  const pathname=usePathname();
  const originals=useRef(new Map<Text,string>());
  useEffect(()=>{const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node:Node|null;while((node=walker.nextNode())){const text=node as Text;if(!text.parentElement?.closest(".language-switcher,script,style,code,[data-no-translate]")&&!originals.current.has(text)) originals.current.set(text,text.nodeValue||"");}const dictionary=lang==="fr"?fr:lang==="es"?es:{};originals.current.forEach((raw,text)=>{const clean=raw.trim();const own=text.parentElement?.dataset?.[lang];const translated=lang==="en"?clean:(own||dictionary[clean]||clean);const lead=raw.match(/^\s*/)?.[0]||"";const trail=raw.match(/\s*$/)?.[0]||"";text.nodeValue=lead+translated+trail;});document.documentElement.lang=lang;},[lang,pathname]);
  return <div className="language-switcher" aria-label="Language"><button className={lang==="en"?"active":""} onClick={()=>setLanguage("en")}>EN</button><button className={lang==="fr"?"active":""} onClick={()=>setLanguage("fr")}>FR</button><button className={lang==="es"?"active":""} onClick={()=>setLanguage("es")}>ES</button></div>;
}
