import {plans} from "./plans-data";
import SiteFooter from "./site-footer";
import SiteHeader from "./site-header";


const devices=["Smart TV","Android TV","Fire TV","Apple TV","Mobile","Computer"];

export default function Home(){return <main id="main-content">
  <SiteHeader active="home"/>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span/> Online TV service · Support 7 days a week</p><h1>Your entertainment.<br/><em>Simply.</em></h1><p className="hero-lead">Enjoy your content on every screen with fast activation, quality adapted to your connection and a team ready to help.</p><div className="hero-actions"><a className="button" href="#plans">Explore plans <span>→</span></a><a className="text-link" href="#how">How does it work?</a></div><div className="trust-row"><span>✓ Confirm your device first</span><span>✓ Support 7 days a week</span><span>✓ 7-day refund policy</span></div></div><div className="hero-visual"><img className="hero-photo" src="/home-cinema-pro.webp" srcSet="/home-cinema-pro-small.webp 640w, /home-cinema-pro.webp 1200w" sizes="(max-width: 900px) 100vw, 48vw" width="1200" height="800" fetchPriority="high" alt="Home cinema with a large screen, dark seating and subtle red lighting"/><div className="visual-badge"><b>4K</b><span>Ultra<br/>high definition</span></div><div className="live-pill"><i/> PREMIUM EXPERIENCE</div></div></section>
  <section className="proof" aria-label="How ordering works"><div><strong>01</strong><small>Check compatibility</small></div><div><strong>02</strong><small>Confirm your offer</small></div><div><strong>03</strong><small>Pay through your individual link</small></div><div><strong>04</strong><small>Receive setup instructions</small></div></section>
  <section className="section" id="benefits"><p className="eyebrow"><span/> Why Market Pro</p><h2>Everything you need.<br/><em>Nothing complicated.</em></h2><div className="benefit-grid"><article><b>01</b><h3>Crystal-clear picture</h3><p>SD, HD, Full HD and 4K quality depending on the content, your device and connection.</p></article><article><b>02</b><h3>Your favourite screens</h3><p>A service compatible with connected TVs, mobile devices and computers.</p></article><article><b>03</b><h3>Real guidance</h3><p>Our team guides you through installation and answers your questions.</p></article></div></section>
  <section className="section plans-section" id="plans"><div className="section-heading"><div><p className="eyebrow"><span/> Clear pricing</p><h2>Choose your <em>plan.</em></h2></div><p>Compare the total price for each duration. Player app fees, if needed, are separate. Confirm your device and channel requirements before payment.</p></div><div className="plans">{plans.map(plan=><article className={plan.featured?"plan featured":"plan"} key={plan.duration}>{plan.featured&&<span className="popular">12-month plan</span>}<p>{plan.name}</p><h3>{plan.duration}</h3><strong>{plan.price}</strong><small>USD total · 1 simultaneous connection</small><ul><li>Fast activation</li><li>Live TV and catalogue</li><li>Multi-device compatible</li><li>Support 7 days a week</li></ul><a className={plan.featured?"button":"button button-outline"} href={`/order?plan=${plan.id}`}>Choose this plan</a></article>)}</div></section>
  <section className="device-section" id="devices"><div><p className="eyebrow light"><span/> Everywhere with you</p><h2>One subscription.<br/><em>All your screens.</em></h2><p>We help you set up the service on your device, step by step.</p></div><div className="device-list">{devices.map((device,i)=><span key={device}><b>{String(i+1).padStart(2,"0")}</b>{device}<i>✓</i></span>)}</div></section>
  <section className="section how" id="how"><p className="eyebrow"><span/> Easy setup</p><h2>Ready in <em>three steps.</em></h2><div className="steps"><article><b>1</b><h3>Choose</h3><p>Select the duration that suits you.</p></article><article><b>2</b><h3>Receive</h3><p>After we check your request, you receive an individual PayPal link. Activation follows confirmed payment.</p></article><article><b>3</b><h3>Enjoy</h3><p>Install the service with help from our team.</p></article></div></section>
  <section className="section confidence"><p className="eyebrow">Before you decide</p><h2>Know what you are buying.</h2><div className="benefit-grid"><article><h3>A clear total price</h3><p>Choose a duration and review the amount before payment. Ask about any separate player fee.</p><a className="text-link" href="/plans">Compare the plans →</a></article><article><h3>Help choosing your setup</h3><p>Send your device model and the channels you need. Confirm availability before placing an order.</p><a className="text-link" href="/contact">Check with support →</a></article><article><h3>Terms you can read first</h3><p>Read the delivery steps and the eligibility conditions of the 7-day refund policy.</p><a className="text-link" href="/before-you-order">Your buying checklist →</a></article></div></section><section className="section"><p className="eyebrow">Practical reading</p><h2>A better start to streaming.</h2><div className="benefit-grid"><article><h3>Choosing a subscription</h3><p>What to check before committing to a plan.</p><a href="/blog/choose-tv-subscription" className="text-link">Read the checklist →</a></article><article><h3>Stop the buffering</h3><p>Seven checks to identify where playback goes wrong.</p><a href="/blog/fix-streaming-buffering" className="text-link">Troubleshoot playback →</a></article><article><h3>Wi-Fi or Ethernet?</h3><p>How to test the connection at your television.</p><a href="/blog/wifi-or-ethernet-streaming" className="text-link">Compare connections →</a></article></div></section>
  <section className="section faq" id="faq"><div><p className="eyebrow"><span/> Frequently asked questions</p><h2>Need some<br/><em>clarification?</em></h2><p>Our team is available if you cannot find your answer here.</p><a className="text-link" href="/contact">Contact support →</a></div><div className="questions"><details open><summary>Which devices are compatible?<span>+</span></summary><p>Smart TV, Android TV, Fire TV, Apple TV, smartphones, tablets and computers.</p></details><details><summary>What internet speed do I need?<span>+</span></summary><p>A stable connection is essential. Available quality depends on your speed and device.</p></details><details><summary>Do you offer a guarantee?<span>+</span></summary><p>Refund requests for a first purchase must be made within 7 calendar days of activation and meet the eligibility conditions in our refund policy.</p><a href="/refund-policy">Read the refund conditions →</a></details></div></section>
  <SiteFooter/>
</main>}
