import SiteHeader from "./site-header";

const plans=[{name:"Discovery",duration:"1 month",price:"$14"},{name:"Essential",duration:"3 months",price:"$24"},{name:"Comfort",duration:"6 months",price:"$34"},{name:"Premium",duration:"12 months",price:"$49",featured:true}];
const devices=["Smart TV","Android TV","Fire TV","Apple TV","Mobile","Computer"];

export default function Home(){return <main>
  <SiteHeader active="home"/>
  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span/> Online TV service · Support 7 days a week</p><h1>Your entertainment.<br/><em>Simply.</em></h1><p className="hero-lead">Enjoy your content on every screen with fast activation, quality adapted to your connection and a team ready to help.</p><div className="hero-actions"><a className="button" href="#plans">Explore plans <span>→</span></a><a className="text-link" href="#how">How does it work?</a></div><div className="trust-row"><span>✓ Fast activation</span><span>✓ Support 7 days a week</span><span>✓ 7-day guarantee</span></div></div><div className="hero-visual" aria-label="Modern red-lit cinema room displaying IBO Player Pro"><div className="visual-badge"><b>4K</b><span>Ultra<br/>high definition</span></div><div className="live-pill"><i/> PREMIUM EXPERIENCE</div></div></section>
  <section className="proof" aria-label="Key figures"><div><strong>30K<span>+</span></strong><small>international channels</small></div><div><strong>40K<span>+</span></strong><small>movies and series</small></div><div><strong>99.9<span>%</span></strong><small>announced availability</small></div><div><strong>7<span>/7</span></strong><small>responsive support</small></div></section>
  <section className="section" id="benefits"><p className="eyebrow"><span/> Why Market Pro</p><h2>Everything you need.<br/><em>Nothing complicated.</em></h2><div className="benefit-grid"><article><b>01</b><h3>Crystal-clear picture</h3><p>SD, HD, Full HD and 4K quality depending on the content, your device and connection.</p></article><article><b>02</b><h3>Your favourite screens</h3><p>A service compatible with connected TVs, mobile devices and computers.</p></article><article><b>03</b><h3>Real guidance</h3><p>Our team guides you through installation and answers your questions.</p></article></div></section>
  <section className="section plans-section" id="plans"><div className="section-heading"><div><p className="eyebrow"><span/> Clear pricing</p><h2>Choose your <em>plan.</em></h2></div><p>Every plan includes the same features. Only the duration changes.</p></div><div className="plans">{plans.map(plan=><article className={plan.featured?"plan featured":"plan"} key={plan.duration}>{plan.featured&&<span className="popular">Most popular</span>}<p>{plan.name}</p><h3>{plan.duration}</h3><strong>{plan.price}</strong><small>per connection</small><ul><li>Fast activation</li><li>Live TV and catalogue</li><li>Multi-device compatible</li><li>Support 7 days a week</li></ul><a className={plan.featured?"button":"button button-outline"} href="/contact">Choose this plan</a></article>)}</div></section>
  <section className="device-section" id="devices"><div><p className="eyebrow light"><span/> Everywhere with you</p><h2>One subscription.<br/><em>All your screens.</em></h2><p>We help you set up the service on your device, step by step.</p></div><div className="device-list">{devices.map((device,i)=><span key={device}><b>{String(i+1).padStart(2,"0")}</b>{device}<i>✓</i></span>)}</div></section>
  <section className="section how" id="how"><p className="eyebrow"><span/> Easy setup</p><h2>Ready in <em>three steps.</em></h2><div className="steps"><article><b>1</b><h3>Choose</h3><p>Select the duration that suits you.</p></article><article><b>2</b><h3>Receive</h3><p>Your access details and instructions arrive quickly.</p></article><article><b>3</b><h3>Enjoy</h3><p>Install the service with help from our team.</p></article></div></section>
  <section className="reviews section"><div className="section-heading"><div><p className="eyebrow"><span/> Customer reviews</p><h2>An experience that<br/><em>makes a difference.</em></h2></div><p className="demo-note">Customer reviews</p></div><div className="review-grid"><article><div className="stars">★★★★★</div><p>“Fast installation and very clear guidance. Everything was ready in just a few minutes.”</p><footer><span>ML</span><div><b>Marie L.</b><small>Review from · France</small></div></footer></article><article className="review-hot"><div className="stars">★★★★★</div><p>“The picture is smooth and support guided me through setup on my Smart TV.”</p><footer><span>KB</span><div><b>Karim B.</b><small>Review from · Belgium</small></div></footer></article><article><div className="stars">★★★★★</div><p>“A simple interface, a wide choice and, above all, a team that is available.”</p><footer><span>SN</span><div><b>Sofia N.</b><small>Review from · Switzerland</small></div></footer></article></div></section>
  <section className="section faq" id="faq"><div><p className="eyebrow"><span/> Frequently asked questions</p><h2>Need some<br/><em>clarification?</em></h2><p>Our team is available if you cannot find your answer here.</p><a className="text-link" href="/contact">Contact support →</a></div><div className="questions"><details open><summary>Which devices are compatible?<span>+</span></summary><p>Smart TV, Android TV, Fire TV, Apple TV, smartphones, tablets and computers.</p></details><details><summary>What internet speed do I need?<span>+</span></summary><p>A stable connection is essential. Available quality depends on your speed and device.</p></details><details><summary>Do you offer a guarantee?<span>+</span></summary><p>Yes. Subscriptions include a 7-day money-back guarantee, subject to our terms.</p></details></div></section>
  <footer><a className="brand" href="/"><span className="brand-mark"><img src="/market-pro-logo.png" alt="Market Pro logo"/></span><span>MARKET <b>PRO</b></span></a><p>A simple, smooth and supported TV experience.</p><div><a href="/about-us">About us</a><a href="/terms-of-service">Terms</a><a href="/privacy-policy">Privacy</a><a href="/delivery-policy">Delivery</a><a href="/refund-policy">Refunds</a><a href="/dmca">DMCA</a></div><small>© 2026 Market Pro. All rights reserved. Use this service only for content you are authorised to access.</small></footer>
</main>}
