import type {Metadata} from 'next';
import {plans} from "./plans-data";

import SiteFooter from "./site-footer";

import SiteHeader from "./site-header";





const devices=["Smart TV","Android TV","Fire TV","Apple TV","Mobile","Computer"];



export const metadata: Metadata = {
  title: 'IPTV subscription: compare plans, devices and streaming quality',
  description: 'Choose an IPTV subscription with clear checks for price, compatible devices, picture quality and support. Compare Market Pro plans before requesting an order.',
  alternates: {canonical: '/'},
};

export default function Home(){return <main id="main-content" className="subscription-home">

  <link rel="preload" as="image" href="/home-cinema-pro.webp" imageSrcSet="/home-cinema-pro-small.webp 640w, /home-cinema-pro.webp 1200w" imageSizes="(max-width: 900px) 100vw, 48vw" fetchPriority="high"/><SiteHeader active="home"/>

  <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow"><span/> Online TV service · Support 7 days a week</p><h1>Choose an IPTV subscription<br/><em>that fits your setup.</em></h1><p className="hero-lead">Start with what you want to watch, the device you already own and the full cost. Check the details before choosing a duration.</p><div className="hero-actions"><a className="button" href="#plans">Explore plans <span>→</span></a><a className="text-link" href="#how">How does it work?</a></div><div className="trust-row"><span>✓ Confirm your device first</span><span>✓ Support 7 days a week</span><span>✓ 7-day refund policy</span></div></div><div className="hero-visual"><img className="hero-photo" src="/home-cinema-pro.webp" srcSet="/home-cinema-pro-small.webp 640w, /home-cinema-pro.webp 1200w" sizes="(max-width: 900px) 100vw, 48vw" width="1200" height="800" fetchPriority="high" alt="Home cinema with a large screen, dark seating and subtle red lighting"/><div className="visual-badge"><b>4K</b><span>Ultra<br/>high definition</span></div><div className="live-pill"><i/> PREMIUM EXPERIENCE</div></div></section>

  <section className="proof" aria-label="How ordering works"><div><strong>01</strong><small>Check compatibility</small></div><div><strong>02</strong><small>Confirm your offer</small></div><div><strong>03</strong><small>Pay through your individual link</small></div><div><strong>04</strong><small>Receive setup instructions</small></div></section>

  <section className="section" id="benefits"><p className="eyebrow"><span/> Why Market Pro</p><h2>What is an IPTV subscription?</h2><div className="home-section-intro" data-no-translate><p>IPTV delivers television over an internet connection. A subscription provides access to a service for an agreed period; a player is the software used to open that service on a compatible device. Buying a player licence does not by itself include a channel subscription.</p><p>Before ordering, identify the programmes you need and ask whether they are available in your country and on your device. A large catalogue alone does not establish that a particular channel or event is included.</p></div><div className="benefit-grid"><article><b>01</b><h3>Crystal-clear picture</h3><p>SD, HD, Full HD and 4K quality depending on the content, your device and connection.</p></article><article><b>02</b><h3>Your favourite screens</h3><p>A service compatible with connected TVs, mobile devices and computers.</p></article><article><b>03</b><h3>Real guidance</h3><p>Our team guides you through installation and answers your questions.</p></article></div></section>

  <section className="section plans-section" id="plans"><div className="section-heading"><div><p className="eyebrow"><span/> Clear pricing</p><h2>Compare the total cost and commitment</h2></div><p>Compare the total price for each duration. Player app fees, if needed, are separate. Confirm your device and channel requirements before payment.</p></div><div className="plans">{plans.map(plan=><article className={plan.featured?"plan featured":"plan"} key={plan.duration}>{plan.featured&&<span className="popular">12-month plan</span>}<p>{plan.name}</p><h3>{plan.duration}</h3><strong>{plan.price}</strong><small>USD total · 1 simultaneous connection</small><ul><li>Fast activation</li><li>Live TV and catalogue</li><li>Multi-device compatible</li><li>Support 7 days a week</li></ul><a className={plan.featured?"button":"button button-outline"} href={`/order?plan=${plan.id}`}>Choose this plan</a></article>)}</div></section>

  <section className="device-section" id="devices"><div><p className="eyebrow light"><span/> Everywhere with you</p><h2>Check your device before paying</h2><div className="home-section-intro" data-no-translate><p>Send support the exact television or streaming-device model and the name of your player. Availability can differ between model years and app stores. Confirm whether you need a separate player licence and whether the setup works with the equipment you have.</p><p>Our <a href="/setup">device setup guides</a> explain the basic steps. For a fuller buying checklist, read <a href="/blog/choose-tv-subscription">what to check before choosing a subscription</a>.</p></div><p>We help you set up the service on your device, step by step.</p></div><div className="device-list">{devices.map((device,i)=><span key={device}><b>{String(i+1).padStart(2,"0")}</b>{device}<i>✓</i></span>)}</div></section>

  <section className="section how" id="how"><p className="eyebrow"><span/> Easy setup</p><h2>Know what happens after your request</h2><div className="home-section-intro" data-no-translate><p>The Market Pro order form starts a request; it does not take payment. Support checks your requirements before sending an individual PayPal payment link. Read the <a href="/delivery-policy">delivery process</a> and <a href="/refund-policy">refund conditions</a> before deciding.</p><p>Ask about your country, required channels, device and number of screens. Keep the confirmation so you can refer to the agreed details later.</p></div><div className="steps"><article><b>1</b><h3>Choose</h3><p>Select the duration that suits you.</p></article><article><b>2</b><h3>Receive</h3><p>After we check your request, you receive an individual PayPal link. Activation follows confirmed payment.</p></article><article><b>3</b><h3>Enjoy</h3><p>Install the service with help from our team.</p></article></div></section>

  <section className="section confidence"><p className="eyebrow">Before you decide</p><h2>Choose a useful picture quality</h2><div className="home-section-intro" data-no-translate><p>The source, player, display and connection all affect the picture you can watch. A 4K television does not turn every stream into native 4K, and a higher advertised resolution does not guarantee smoother playback.</p><p>Read <a href="/blog/hd-full-hd-4k-guide">HD vs Full HD vs 4K</a> to understand the tradeoffs before choosing equipment or changing your internet plan.</p></div><div className="benefit-grid"><article><h3>HD and Full HD</h3><p>Choose a quality that your source, player and screen support reliably.</p><a className="text-link" href="/blog/hd-full-hd-4k-guide">Compare picture quality →</a></article><article><h3>4K depends on your setup</h3><p>A 4K screen does not make every stream native 4K. Check the source and device compatibility.</p><a className="text-link" href="/setup">Check your device →</a></article><article><h3>Stability comes first</h3><p>Compare Wi-Fi and Ethernet before paying for new equipment or a faster internet plan.</p><a className="text-link" href="/blog/wifi-or-ethernet-streaming">Check your connection →</a></article></div></section><section className="section"><p className="eyebrow">Practical reading</p><h2>If streaming keeps buffering, investigate first</h2><div className="home-section-intro" data-no-translate><p>Repeated pauses can involve the local network, viewing device or individual stream. Compare another programme and another app on the same device, then try a wired connection where supported. Buying another subscription may not resolve a local Wi-Fi problem.</p><p>Follow our <a href="/blog/fix-streaming-buffering">streaming keeps buffering troubleshooting guide</a> and record the results before contacting support.</p></div><div className="benefit-grid"><article><h3>Choosing a subscription</h3><p>What to check before committing to a plan.</p><a href="/blog/choose-tv-subscription" className="text-link">Read the checklist →</a></article><article><h3>Stop the buffering</h3><p>Seven checks to identify where playback goes wrong.</p><a href="/blog/fix-streaming-buffering" className="text-link">Troubleshoot playback →</a></article><article><h3>Wi-Fi or Ethernet?</h3><p>How to test the connection at your television.</p><a href="/blog/wifi-or-ethernet-streaming" className="text-link">Compare connections →</a></article></div></section>

  <section className="section faq" id="faq"><div><p className="eyebrow"><span/> Frequently asked questions</p><h2>Need some<br/><em>clarification?</em></h2><p>Our team is available if you cannot find your answer here.</p><a className="text-link" href="/contact">Contact support →</a></div><div className="questions"><details open><summary>Which devices are compatible?<span>+</span></summary><p>Smart TV, Android TV, Fire TV, Apple TV, smartphones, tablets and computers.</p></details><details><summary>What internet speed do I need?<span>+</span></summary><p>A stable connection is essential. Available quality depends on your speed and device.</p></details><details><summary>Do you offer a guarantee?<span>+</span></summary><p>Refund requests for a first purchase must be made within 7 calendar days of activation and meet the eligibility conditions in our refund policy.</p><a href="/refund-policy">Read the refund conditions →</a></details></div></section>

<section className="detail-cta"><h2>Ready to check your setup?</h2><p>Have your device model and viewing requirements ready. We can help you check them before payment.</p><a className="button" href="/contact">Ask about compatibility</a><p><a href="/plans">View all subscription plans â†’</a></p></section>
  <SiteFooter/>

</main>}

